# Generated by Django 4.2.6 on 2023-10-28 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_rename_paleta_pepito'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pepito',
            new_name='Paleta',
        ),
    ]
