# Generated by Django 4.2.6 on 2023-10-31 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automovil', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auto',
            new_name='Automovil',
        ),
    ]
